-- EOA_Data_Herbs.lua
EOA_DATA = EOA_DATA or {}

EOA_DATA.Herbs = {
    {
        id = "herbs_tirisfal_balnir_patch",
        name = "Tirisfal Balnir Patch",
        mapID = 1420,
        x = 0.470,
        y = 0.430,
        type = "FARM",
        category = "HERBS",
        levelMin = 8,
        levelMax = 14,
        skillRequired = 1,
        resource = "Peacebloom/Silverleaf",
        description = "Circle the fields and graveyard approaches near Balnir Farmstead for beginner herbs. Spawns are close together, making this route excellent for fresh herbalists on foot. Run it at level 8-14 to stack starter herbs and early alchemy materials."
    },
    {
        id = "herbs_elwynn_riverbend",
        name = "Elwynn Riverbend Gather",
        mapID = 1429,
        x = 0.430,
        y = 0.650,
        type = "FARM",
        category = "HERBS",
        levelMin = 8,
        levelMax = 14,
        skillRequired = 1,
        resource = "Peacebloom/Silverleaf",
        description = "Follow creeks and farm borders around Goldshire for abundant low-skill herbs. The route is forgiving and easy to repeat while completing nearby quests. Recommended level 8-14 for clean early herbalism progression."
    },
    {
        id = "herbs_mulgore_plains_loop",
        name = "Mulgore Plains Loop",
        mapID = 1412,
        x = 0.460,
        y = 0.580,
        type = "FARM",
        category = "HERBS",
        levelMin = 10,
        levelMax = 16,
        skillRequired = 1,
        resource = "Peacebloom/Earthroot",
        description = "The broad grasslands of Mulgore provide simple herb lines with low mob pressure. Earthroot appears near rocky breaks, letting you diversify quickly from starter plants. Level 10-16 characters can gather continuously with minimal travel risk."
    },
    {
        id = "herbs_darkshore_twilight_grove",
        name = "Darkshore Twilight Grove",
        mapID = 1439,
        x = 0.430,
        y = 0.360,
        type = "FARM",
        category = "HERBS",
        levelMin = 12,
        levelMax = 18,
        skillRequired = 15,
        resource = "Mageroyal/Briarthorn",
        description = "Work the forest edges and ruined roads for mageroyal clusters and briarthorn patches. This path scales well because nodes are visible from distance in open clearings. Farm here at level 12-18 to push herbalism toward mid-tier recipes."
    },
    {
        id = "herbs_westfall_field_ring",
        name = "Westfall Field Ring",
        mapID = 1436,
        x = 0.490,
        y = 0.310,
        type = "FARM",
        category = "HERBS",
        levelMin = 14,
        levelMax = 20,
        skillRequired = 15,
        resource = "Mageroyal/Briarthorn",
        description = "This route loops old farms and road shoulders where briarthorn appears in clusters. Defias patrols can be ignored by mounted players, improving lap speed significantly. Recommended level 14-20 for efficient herb collection and quest overlap."
    },
    {
        id = "herbs_silverpine_forest_road",
        name = "Silverpine Forest Roadline",
        mapID = 1421,
        x = 0.470,
        y = 0.620,
        type = "FARM",
        category = "HERBS",
        levelMin = 16,
        levelMax = 22,
        skillRequired = 50,
        resource = "Bruiseweed/Briarthorn",
        description = "Follow the road corridor and nearby hills for steady bruiseweed spawns. Wolf packs are manageable, and the zone layout supports long uninterrupted circles. Level 16-22 is ideal for building herb stock used in early healing potions."
    },
    {
        id = "herbs_loch_modan_northshore",
        name = "Loch Modan Northshore",
        mapID = 1432,
        x = 0.360,
        y = 0.240,
        type = "FARM",
        category = "HERBS",
        levelMin = 18,
        levelMax = 24,
        skillRequired = 50,
        resource = "Bruiseweed/Wild Steelbloom",
        description = "Gather along lake ridges and mountain toes for a balanced bruiseweed route with steelbloom upgrades. The loop is compact and easy to reset by cutting across the dam side. Farm at level 18-24 for consistent gains into higher-skill herbs."
    },
    {
        id = "herbs_redridge_raven_hill",
        name = "Redridge Raven Hill Path",
        mapID = 1433,
        x = 0.360,
        y = 0.560,
        type = "FARM",
        category = "HERBS",
        levelMin = 20,
        levelMax = 26,
        skillRequired = 70,
        resource = "Bruiseweed/Wild Steelbloom",
        description = "Redridge slopes and ravine edges hold many steelbloom nodes near exposed stone. Gnoll camps create pressure points, so route around high-density camps when crowded. Recommended for level 20-26 herbalists climbing toward Kingsblood and beyond."
    },
    {
        id = "herbs_stonetalon_windshear_line",
        name = "Stonetalon Windshear Line",
        mapID = 1419,
        x = 0.600,
        y = 0.530,
        type = "FARM",
        category = "HERBS",
        levelMin = 22,
        levelMax = 28,
        skillRequired = 85,
        resource = "Kingsblood/Liferoot",
        description = "Move between forest breaks and creek beds for kingsblood with occasional liferoot pickups. The route is narrow but very repeatable, making it good for disciplined lap timing. Level 22-28 characters can farm smoothly while questing in nearby hubs."
    },
    {
        id = "herbs_ashenvale_felfire_hill",
        name = "Ashenvale Felfire Hill Loop",
        mapID = 1440,
        x = 0.330,
        y = 0.250,
        type = "FARM",
        category = "HERBS",
        levelMin = 24,
        levelMax = 30,
        skillRequired = 100,
        resource = "Kingsblood/Liferoot",
        description = "Ashenvale roads and shadowed clearings provide a strong kingsblood baseline. Liferoot appears around streams, rewarding players who include water-side detours. Farm here at level 24-30 for dependable mid-tier herb output."
    },
    {
        id = "herbs_hillsbrad_river_route",
        name = "Hillsbrad River Route",
        mapID = 1424,
        x = 0.500,
        y = 0.400,
        type = "FARM",
        category = "HERBS",
        levelMin = 26,
        levelMax = 32,
        skillRequired = 115,
        resource = "Liferoot/Khadgar's Whisker",
        description = "Trace the riverbanks and foothills for a balanced mix of liferoot and whisker nodes. Hillsbrad's open shape lets you chain long loops with very little dead travel. Recommended level 26-32 for reliable herbs and low route complexity."
    },
    {
        id = "herbs_wetlands_greenbelt",
        name = "Wetlands Greenbelt",
        mapID = 1437,
        x = 0.420,
        y = 0.440,
        type = "FARM",
        category = "HERBS",
        levelMin = 28,
        levelMax = 34,
        skillRequired = 115,
        resource = "Liferoot/Khadgar's Whisker",
        description = "Marsh channels and elevated road edges in Wetlands hide many whisker spawns. Crocolisk pressure is manageable if you keep to drier, open ground between pools. Level 28-34 herbalists can maintain a steady gather rate across full laps."
    },
    {
        id = "herbs_stranglethorn_north_jungle",
        name = "Stranglethorn North Jungle",
        mapID = 1434,
        x = 0.400,
        y = 0.230,
        type = "FARM",
        category = "HERBS",
        levelMin = 30,
        levelMax = 36,
        skillRequired = 125,
        resource = "Khadgar's Whisker/Goldthorn",
        description = "Gather along jungle trails and hill cuts where whisker and early goldthorn overlap. Visibility is lower under canopy, so keep a fixed path to avoid missed node pockets. Farm at level 30-36 for efficient progression into advanced alchemy herbs."
    },
    {
        id = "herbs_arathi_highland_ring",
        name = "Arathi Highland Ring",
        mapID = 1417,
        x = 0.550,
        y = 0.380,
        type = "FARM",
        category = "HERBS",
        levelMin = 32,
        levelMax = 38,
        skillRequired = 125,
        resource = "Goldthorn/Khadgar's Whisker",
        description = "Arathi's ridges and ruins support one of the cleanest goldthorn circuits in this bracket. The broad zone shape favors mount users who can hold momentum through long straight segments. Recommended level 32-38 for strong herb-per-hour and easy navigation."
    },
    {
        id = "herbs_desolace_kodo_tracks",
        name = "Desolace Kodo Tracks",
        mapID = 1443,
        x = 0.560,
        y = 0.500,
        type = "FARM",
        category = "HERBS",
        levelMin = 34,
        levelMax = 40,
        skillRequired = 135,
        resource = "Goldthorn/Wintersbite",
        description = "Route from Kodo Graveyard through valley edges for mixed goldthorn and wintersbite. Sparse population keeps competition low, which is ideal for uninterrupted farming sessions. Level 34-40 herbalists can farm here comfortably with little interference."
    },
    {
        id = "herbs_badlands_crag_route",
        name = "Badlands Crag Route",
        mapID = 1418,
        x = 0.430,
        y = 0.450,
        type = "FARM",
        category = "HERBS",
        levelMin = 36,
        levelMax = 42,
        skillRequired = 150,
        resource = "Goldthorn/Firebloom",
        description = "Badlands cliffs provide goldthorn with frequent firebloom near hotter ground and gullies. The route is straightforward and rewards wide loops around canyon walls. Farm at level 36-42 to secure ingredients for key offensive elixirs."
    },
    {
        id = "herbs_swamp_of_sorrows_marsh_ring",
        name = "Swamp of Sorrows Marsh Ring",
        mapID = 1435,
        x = 0.500,
        y = 0.600,
        type = "FARM",
        category = "HERBS",
        levelMin = 38,
        levelMax = 44,
        skillRequired = 160,
        resource = "Blindweed/Khadgar's Whisker",
        description = "Loop the marsh perimeter to collect dense blindweed spawns between pools and ruins. The terrain slows movement, but node density stays high when you commit to full circuits. Recommended level 38-44 for valuable potion and utility herb supply."
    },
    {
        id = "herbs_tanaris_dune_bloom",
        name = "Tanaris Dune Bloom",
        mapID = 1446,
        x = 0.520,
        y = 0.300,
        type = "FARM",
        category = "HERBS",
        levelMin = 40,
        levelMax = 46,
        skillRequired = 205,
        resource = "Firebloom/Purple Lotus",
        description = "Sweep dune ridges and ruin edges for firebloom with pockets of purple lotus. Wide visibility makes it easy to adjust route in response to other gatherers. Level 40-46 is ideal for consistent mid-high herb farming in open terrain."
    },
    {
        id = "herbs_hinterlands_emerald_vale",
        name = "The Hinterlands Emerald Vale",
        mapID = 1425,
        x = 0.580,
        y = 0.470,
        type = "FARM",
        category = "HERBS",
        levelMin = 42,
        levelMax = 48,
        skillRequired = 205,
        resource = "Ghost Mushroom/Goldthorn",
        description = "Caves and shaded valleys in the Hinterlands hold ghost mushroom opportunities alongside goldthorn. The route is more technical, but rewards players who include cave checks each lap. Farm here at level 42-48 for profitable rare herb pulls."
    },
    {
        id = "herbs_feralas_central_circuit",
        name = "Feralas Central Circuit",
        mapID = 1444,
        x = 0.480,
        y = 0.420,
        type = "FARM",
        category = "HERBS",
        levelMin = 44,
        levelMax = 50,
        skillRequired = 210,
        resource = "Sungrass/Ghost Mushroom",
        description = "Move between ruins, road bends, and cave mouths to gather sungrass and ghost mushroom. Feralas offers balanced herb density with enough space to avoid route congestion. Recommended level 44-50 for versatile herb farming and alchemy prep."
    },
    {
        id = "herbs_azshara_cliffside_route",
        name = "Azshara Cliffside Route",
        mapID = 1447,
        x = 0.430,
        y = 0.580,
        type = "FARM",
        category = "HERBS",
        levelMin = 46,
        levelMax = 52,
        skillRequired = 230,
        resource = "Sungrass/Dreamfoil",
        description = "Azshara's long cliffs hide dreamfoil and sungrass in high-value linear segments. Low quest traffic helps preserve nodes for dedicated gatherers. Level 46-52 herbalists can farm here with excellent consistency in long sessions."
    },
    {
        id = "herbs_felwood_north_south_line",
        name = "Felwood North-South Line",
        mapID = 1448,
        x = 0.500,
        y = 0.300,
        type = "FARM",
        category = "HERBS",
        levelMin = 48,
        levelMax = 54,
        skillRequired = 230,
        resource = "Dreamfoil/Gromsblood",
        description = "This classic north-south lane produces steady dreamfoil with frequent gromsblood near demon camps. Keep movement tight through choke points to avoid overpulls from satyrs and corrupted beasts. Farm at level 48-54 for reliable high-tier herb value."
    },
    {
        id = "herbs_western_plaguelands_farm_ring",
        name = "Western Plaguelands Farm Ring",
        mapID = 1422,
        x = 0.470,
        y = 0.530,
        type = "FARM",
        category = "HERBS",
        levelMin = 50,
        levelMax = 56,
        skillRequired = 250,
        resource = "Plaguebloom/Arthas' Tears",
        description = "Circle plague farms and ruined roads for plaguebloom clusters with arthas' tears support. Undead density is high, but routes remain efficient with controlled pulls and mounted movement. Recommended level 50-56 for premium endgame herb stockpiles."
    },
    {
        id = "herbs_burning_steppes_ash_fields",
        name = "Burning Steppes Ash Fields",
        mapID = 1428,
        x = 0.530,
        y = 0.450,
        type = "FARM",
        category = "HERBS",
        levelMin = 52,
        levelMax = 58,
        skillRequired = 250,
        resource = "Gromsblood/Dreamfoil",
        description = "Ashen fields and dragonkin corridors produce dependable gromsblood with dreamfoil overlap. Route danger is high, so this area favors geared farmers with strong sustain. Level 52-58 players can convert risk into very strong herb returns."
    },
    {
        id = "herbs_eastern_plaguelands_corridor",
        name = "Eastern Plaguelands Corridor",
        mapID = 1423,
        x = 0.550,
        y = 0.620,
        type = "FARM",
        category = "HERBS",
        levelMin = 54,
        levelMax = 60,
        skillRequired = 260,
        resource = "Plaguebloom/Dreamfoil",
        description = "Disease-scarred roads and chapelside terrain support one of the best plaguebloom circuits in Classic Era. Travel is efficient when you commit to a full loop through eastern and central lanes. Farm at level 54-60 for top-end herb value and raid consumable demand."
    },
    {
        id = "herbs_winterspring_frostleaf_way",
        name = "Winterspring Frostleaf Way",
        mapID = 1452,
        x = 0.580,
        y = 0.500,
        type = "FARM",
        category = "HERBS",
        levelMin = 55,
        levelMax = 60,
        skillRequired = 270,
        resource = "Icecap/Mountain Silversage",
        description = "Snow ridges and frozen valleys in Winterspring hold valuable icecap and silversage nodes. Long visibility lets you optimize laps quickly when routes are contested. Recommended level 55-60 for premium flask and resistance recipe herbs."
    },
}
