-- EOA_Data_Grind.lua
EOA_DATA = EOA_DATA or {}

EOA_DATA.Grind = {
    {
        id = "grind_loch_modan_trogg_line",
        name = "Loch Modan Trogg Line",
        mapID = 1432,
        x = 0.350,
        y = 0.200,
        type = "FARM",
        levelMin = 14,
        levelMax = 20,
        skillRequired = nil,
        resource = nil,
        description = "Trogg packs in the northern caves are tightly grouped and easy to chain for efficient experience. The cave layout supports short loops with almost no travel downtime. Recommended for level 14-20 when you want simple, consistent grinding."
    },
    {
        id = "grind_barrens_quilboar_pens",
        name = "Barrens Quilboar Pens",
        mapID = 1413,
        x = 0.450,
        y = 0.280,
        type = "FARM",
        levelMin = 16,
        levelMax = 22,
        skillRequired = nil,
        resource = nil,
        description = "Quilboar camps in central Barrens give fast kills and good cloth plus vendor loot. You can maintain uninterrupted pulls by rotating between two adjacent camp clusters. Level 16-22 players can grind here with very stable kill tempo."
    },
    {
        id = "grind_redridge_blackrock_orcs",
        name = "Redridge Blackrock Orcs",
        mapID = 1433,
        x = 0.730,
        y = 0.410,
        type = "FARM",
        levelMin = 18,
        levelMax = 24,
        skillRequired = nil,
        resource = nil,
        description = "Blackrock camps in Redridge are classic humanoid grind targets with reliable respawns. The open camp design makes it easy to avoid dangerous multi-pulls. Farm this at level 18-24 for strong XP and solid coin flow."
    },
    {
        id = "grind_stonetalon_harpies",
        name = "Stonetalon Harpy Roosts",
        mapID = 1419,
        x = 0.480,
        y = 0.420,
        type = "FARM",
        levelMin = 20,
        levelMax = 26,
        skillRequired = nil,
        resource = nil,
        description = "Harpy pockets in Stonetalon provide dense packs and low travel between fights. Casters should line-of-sight around rocks to keep incoming damage manageable. Recommended level 20-26 for a smooth grinding bracket."
    },
    {
        id = "grind_duskwood_worgen_fields",
        name = "Duskwood Worgen Fields",
        mapID = 1431,
        x = 0.740,
        y = 0.460,
        type = "FARM",
        levelMin = 22,
        levelMax = 28,
        skillRequired = nil,
        resource = nil,
        description = "Worgen in open fields offer predictable pulls and quick respawns for sustained combat. Pathing space is generous, which helps melee classes avoid accidental extra packs. Farm here at level 22-28 for clean XP gains and light loot income."
    },
    {
        id = "grind_hillsbrad_syndicate",
        name = "Hillsbrad Syndicate Highway",
        mapID = 1424,
        x = 0.520,
        y = 0.340,
        type = "FARM",
        levelMin = 24,
        levelMax = 30,
        skillRequired = nil,
        resource = nil,
        description = "Syndicate camps around the roads have high humanoid density and quick respawn cycles. The route supports a comfortable clockwise grind with little dead time. Level 24-30 is excellent for XP while farming wool and silk cloth."
    },
    {
        id = "grind_ashenvale_satyrnaar",
        name = "Ashenvale Satyrnaar",
        mapID = 1440,
        x = 0.810,
        y = 0.490,
        type = "FARM",
        levelMin = 26,
        levelMax = 32,
        skillRequired = nil,
        resource = nil,
        description = "Satyr camps in eastern Ashenvale provide dense melee and caster mixes for efficient rotations. Pulling camp edges first keeps pressure low while preserving nonstop kill pace. Recommended level 26-32 for strong grind sessions with good loot value."
    },
    {
        id = "grind_wetlands_orc_camp",
        name = "Wetlands Dragonmaw Camp",
        mapID = 1437,
        x = 0.510,
        y = 0.620,
        type = "FARM",
        levelMin = 28,
        levelMax = 34,
        skillRequired = nil,
        resource = nil,
        description = "Dragonmaw camps are packed with humanoids that respawn quickly and drop useful cloth. Terrain is flat, allowing smooth pull chains for all class types. Farm at level 28-34 for dependable XP and bag-filling loot."
    },
    {
        id = "grind_stranglethorn_venture_co",
        name = "Stranglethorn Venture Co.",
        mapID = 1434,
        x = 0.470,
        y = 0.300,
        type = "FARM",
        levelMin = 30,
        levelMax = 36,
        skillRequired = nil,
        resource = nil,
        description = "Venture Co. camps offer excellent humanoid density with convenient pathing routes between tents. Mobs are close enough for chain pulls but spread enough to avoid accidental overpulls. Level 30-36 players can grind very efficiently here."
    },
    {
        id = "grind_arathi_ogre_mound",
        name = "Arathi Ogre Mound",
        mapID = 1417,
        x = 0.520,
        y = 0.740,
        type = "FARM",
        levelMin = 32,
        levelMax = 38,
        skillRequired = nil,
        resource = nil,
        description = "Boulderfist ogres in Arathi remain a reliable grind location due to compact camp design. Their steady loot table supports both XP progression and practical vendor income. Recommended level 32-38 for durable and predictable farming."
    },
    {
        id = "grind_desolace_centaur_fields",
        name = "Desolace Centaur Fields",
        mapID = 1443,
        x = 0.700,
        y = 0.730,
        type = "FARM",
        levelMin = 34,
        levelMax = 40,
        skillRequired = nil,
        resource = nil,
        description = "Centaur villages in southern Desolace support wide loop routes with constant target availability. Respawns are quick enough to keep combat nearly continuous at peak times. Level 34-40 characters can expect smooth XP and steady coin gains."
    },
    {
        id = "grind_badlands_dustbelch",
        name = "Badlands Dustbelch Ogres",
        mapID = 1418,
        x = 0.160,
        y = 0.550,
        type = "FARM",
        levelMin = 36,
        levelMax = 42,
        skillRequired = nil,
        resource = nil,
        description = "Dustbelch ogres provide thick camp clusters and straightforward line pulls. The area has enough space for kiting and safe resets when needed. Farm here at level 36-42 for dependable XP and cloth drops."
    },
    {
        id = "grind_dustwallow_mirefin",
        name = "Dustwallow Mirefin Murlocs",
        mapID = 1445,
        x = 0.560,
        y = 0.210,
        type = "FARM",
        levelMin = 38,
        levelMax = 44,
        skillRequired = nil,
        resource = nil,
        description = "Mirefin villages near the coast offer fast murloc kills with high target density. Pull spacing is forgiving, enabling long grind sessions without major risk spikes. Recommended level 38-44 for a stable mid-game grind route."
    },
    {
        id = "grind_tanaris_southsea_pirates",
        name = "Southsea Pirates (Tanaris)",
        mapID = 1446,
        x = 0.730,
        y = 0.460,
        type = "FARM",
        levelMin = 40,
        levelMax = 46,
        skillRequired = nil,
        resource = nil,
        description = "Southsea camps are one of the most efficient humanoid grinds for this bracket. Quick respawns and compact camp layout make it easy to maintain nonstop pulls. Level 40-46 players can earn strong XP and cloth with minimal travel."
    },
    {
        id = "grind_feralas_woodpaw",
        name = "Feralas Woodpaw Gnolls",
        mapID = 1444,
        x = 0.730,
        y = 0.560,
        type = "FARM",
        levelMin = 42,
        levelMax = 48,
        skillRequired = nil,
        resource = nil,
        description = "Woodpaw camps in eastern Feralas provide dense humanoid pulls and strong loot cadence. The forested terrain still allows efficient routing once camp order is learned. Farm at level 42-48 for steady XP and mageweave income."
    },
    {
        id = "grind_hinterlands_trolls",
        name = "Hinterlands Witherbark Trolls",
        mapID = 1425,
        x = 0.620,
        y = 0.690,
        type = "FARM",
        levelMin = 44,
        levelMax = 50,
        skillRequired = nil,
        resource = nil,
        description = "Witherbark ruins have heavy troll density and consistent respawns for uninterrupted grinding. Pull routes can chain across several ruins before resetting at the first camp. Recommended level 44-50 for efficient XP and loot in one loop."
    },
    {
        id = "grind_searing_gorge_dark_iron",
        name = "Searing Gorge Dark Iron Camps",
        mapID = 1427,
        x = 0.380,
        y = 0.520,
        type = "FARM",
        levelMin = 46,
        levelMax = 52,
        skillRequired = nil,
        resource = nil,
        description = "Dark Iron camps are tightly packed and ideal for high-tempo grind rotations. The zone is dangerous, but rewards players with strong kill chains and useful drops. Level 46-52 is a strong window to farm here efficiently."
    },
    {
        id = "grind_blasted_lands_ogres",
        name = "Blasted Lands Ogres",
        mapID = 1419,
        x = 0.510,
        y = 0.300,
        type = "FARM",
        levelMin = 48,
        levelMax = 54,
        skillRequired = nil,
        resource = nil,
        description = "The ogre camps in Blasted Lands have dependable spawn rates and good vendor loot. Open paths between camps keep movement smooth for long farming sessions. Farm at level 48-54 for solid XP and steady gold."
    },
    {
        id = "grind_ungoro_dino_circuit",
        name = "Un'Goro Dino Circuit",
        mapID = 1449,
        x = 0.620,
        y = 0.680,
        type = "FARM",
        levelMin = 50,
        levelMax = 56,
        skillRequired = nil,
        resource = nil,
        description = "Un'Goro's beast routes support nonstop grinding with strong leather and vendor drops. The circular terrain naturally guides efficient pull loops around the crater. Recommended level 50-56 for high uptime and strong raw farming value."
    },
    {
        id = "grind_felwood_jadefire",
        name = "Jadefire Satyrs (Felwood)",
        mapID = 1448,
        x = 0.410,
        y = 0.570,
        type = "FARM",
        levelMin = 52,
        levelMax = 58,
        skillRequired = nil,
        resource = nil,
        description = "Jadefire satyrs are a proven late-game grind for cloth, coin, and utility drops. Camps are compact enough to maintain high pull frequency without long runs. Level 52-58 players can sustain excellent farm efficiency here."
    },
    {
        id = "grind_burning_steppes_blackrock",
        name = "Burning Steppes Blackrock",
        mapID = 1428,
        x = 0.650,
        y = 0.420,
        type = "FARM",
        levelMin = 53,
        levelMax = 59,
        skillRequired = nil,
        resource = nil,
        description = "Blackrock encampments provide strong humanoid density and high-value late-game loot. Controlled pulling is key because patrol overlap can escalate quickly. Farm here at level 53-59 for excellent XP and runecloth generation."
    },
    {
        id = "grind_wpl_felstone_undead",
        name = "Felstone Field Undead",
        mapID = 1422,
        x = 0.380,
        y = 0.560,
        type = "FARM",
        levelMin = 54,
        levelMax = 60,
        skillRequired = nil,
        resource = nil,
        description = "Felstone Field has dense undead pulls with steady respawns and bonus scourge loot potential. The farm layout supports short loops that keep combat nearly constant. Recommended level 54-60 for efficient endgame grinding."
    },
    {
        id = "grind_azshara_legashi",
        name = "Legashi Satyrs (Azshara)",
        mapID = 1447,
        x = 0.590,
        y = 0.780,
        type = "FARM",
        levelMin = 55,
        levelMax = 60,
        skillRequired = nil,
        resource = nil,
        description = "Legashi camps combine strong runecloth rates with high-value satyr drops in one route. Pull density is excellent for advanced solo grinding with minimal downtime. Farm this spot at level 55-60 for premium endgame returns."
    },
    {
        id = "grind_epl_plaguewoods",
        name = "Eastern Plaguelands Plaguewoods",
        mapID = 1423,
        x = 0.240,
        y = 0.760,
        type = "FARM",
        levelMin = 56,
        levelMax = 60,
        skillRequired = nil,
        resource = nil,
        description = "Plaguewoods undead form dense packs ideal for geared characters seeking raw grind efficiency. Routeing between choke points keeps kill chains strong while minimizing travel waste. Level 56-60 players can maintain excellent XP and runecloth output here."
    },
    {
        id = "grind_winterspring_frostmaul",
        name = "Winterspring Frostmaul Giants",
        mapID = 1452,
        x = 0.680,
        y = 0.410,
        type = "FARM",
        levelMin = 57,
        levelMax = 60,
        skillRequired = nil,
        resource = nil,
        description = "Frostmaul giants are a high-end grind target with valuable drops and good spacing for kiting. The area is quieter than many endgame zones, supporting long uninterrupted sessions. Recommended level 57-60 for durable classes farming top-tier raw gold value."
    },
}
