-- EOA_Data_Dungeons.lua
EOA_DATA = EOA_DATA or {}

EOA_DATA.Dungeons = {
    {
        id = "dungeon_deadmines",
        name = "The Deadmines Entrance",
        mapID = 1436,
        x = 0.424,
        y = 0.710,
        type = "DUNGEON",
        levelMin = 17,
        levelMax = 26,
        profession = nil,
        resource = nil,
        tags = { "alliance", "instance", "classic" },
        description = "Moonbrook mine entrance leading into The Deadmines."
    },
    {
        id = "dungeon_shadowfang_keep",
        name = "Shadowfang Keep Entrance",
        mapID = 1421,
        x = 0.451,
        y = 0.680,
        type = "DUNGEON",
        levelMin = 22,
        levelMax = 30,
        profession = nil,
        resource = nil,
        tags = { "horde", "instance", "undead" },
        description = "Castle courtyard gate at Pyrewood approach into Shadowfang Keep."
    },
    {
        id = "dungeon_scarlet_monastery",
        name = "Scarlet Monastery Entrance",
        mapID = 1420,
        x = 0.835,
        y = 0.330,
        type = "DUNGEON",
        levelMin = 26,
        levelMax = 45,
        profession = nil,
        resource = nil,
        tags = { "instance", "wings", "undead" },
        description = "Main gate and courtyard for all Scarlet Monastery wings."
    },
    {
        id = "dungeon_uldaman",
        name = "Uldaman Entrance",
        mapID = 1418,
        x = 0.445,
        y = 0.120,
        type = "DUNGEON",
        levelMin = 35,
        levelMax = 45,
        profession = nil,
        resource = nil,
        tags = { "instance", "titan", "badlands" },
        description = "Badlands canyon portal into Uldaman's surface halls."
    },
    {
        id = "dungeon_blackrock_depths",
        name = "Blackrock Mountain (BRD)",
        mapID = 1428,
        x = 0.345,
        y = 0.845,
        type = "DUNGEON",
        levelMin = 52,
        levelMax = 60,
        profession = nil,
        resource = nil,
        tags = { "instance", "blackrock", "endgame" },
        description = "Blackrock Mountain chain entrance used for Blackrock Depths access."
    },
    {
        id = "dungeon_molten_core",
        name = "Molten Core Attunement Entrance",
        mapID = 1428,
        x = 0.290,
        y = 0.385,
        type = "DUNGEON",
        levelMin = 60,
        levelMax = 60,
        profession = nil,
        resource = nil,
        tags = { "raid", "blackrock", "endgame" },
        description = "Portal area inside Blackrock Depths route to Molten Core."
    },
    {
        id = "dungeon_onyxias_lair",
        name = "Onyxia's Lair Entrance",
        mapID = 1445,
        x = 0.525,
        y = 0.760,
        type = "DUNGEON",
        levelMin = 60,
        levelMax = 60,
        profession = nil,
        resource = nil,
        tags = { "raid", "dragon", "attunement" },
        description = "Cavern entrance in Dustwallow Marsh for Onyxia's Lair."
    },
    {
        id = "dungeon_zulgurub",
        name = "Zul'Gurub Entrance",
        mapID = 1434,
        x = 0.540,
        y = 0.175,
        type = "DUNGEON",
        levelMin = 60,
        levelMax = 60,
        profession = nil,
        resource = nil,
        tags = { "raid", "jungle", "troll" },
        description = "Northern Stranglethorn temple gate into Zul'Gurub."
    },
}
