-- EOA_Data_Cloth.lua
EOA_DATA = EOA_DATA or {}

EOA_DATA.Cloth = {
    {
        id = "cloth_westfall_defias_fields",
        name = "Westfall Defias Fields",
        mapID = 1436,
        x = 0.560,
        y = 0.470,
        type = "FARM",
        category = "CLOTH",
        levelMin = 12,
        levelMax = 18,
        skillRequired = nil,
        resource = "Linen Cloth",
        description = "Defias camps across the fields provide tightly packed humanoid pulls with strong linen yield. Patrol density supports chain pulling even for lower-geared characters. Farm here at level 12-18 to build early cloth stacks for First Aid and Tailoring."
    },
    {
        id = "cloth_barrens_harpy_roost",
        name = "Barrens Harpy Roost",
        mapID = 1413,
        x = 0.410,
        y = 0.150,
        type = "FARM",
        category = "CLOTH",
        levelMin = 14,
        levelMax = 20,
        skillRequired = nil,
        resource = "Linen Cloth",
        description = "Harpy nests in the northern Barrens give quick kills and frequent linen drops. The terrain is open, so it is easy to keep a circular pull pattern without downtime. Recommended level 14-20 for reliable linen and light vendor income."
    },
    {
        id = "cloth_loch_modan_trogg_caves",
        name = "Loch Modan Trogg Caves",
        mapID = 1432,
        x = 0.350,
        y = 0.180,
        type = "FARM",
        category = "CLOTH",
        levelMin = 16,
        levelMax = 22,
        skillRequired = nil,
        resource = "Linen Cloth/Wool Cloth",
        description = "Trogg tunnels near the northern hills offer dense respawns with mixed linen and early wool. Cave routing requires attention, but rewards players with minimal travel time between kills. Farm at level 16-22 for a smooth cloth transition into wool tiers."
    },
    {
        id = "cloth_silverpine_pyrewood",
        name = "Silverpine Pyrewood",
        mapID = 1421,
        x = 0.460,
        y = 0.730,
        type = "FARM",
        category = "CLOTH",
        levelMin = 18,
        levelMax = 24,
        skillRequired = nil,
        resource = "Wool Cloth",
        description = "Pyrewood villagers and nearby humanoids provide consistent wool in compact clusters. The route is easy to repeat and has enough targets to avoid respawn waiting. Level 18-24 players can secure large wool amounts for profession recipes."
    },
    {
        id = "cloth_redridge_blackrock_camp",
        name = "Redridge Blackrock Camp",
        mapID = 1433,
        x = 0.730,
        y = 0.430,
        type = "FARM",
        category = "CLOTH",
        levelMin = 20,
        levelMax = 26,
        skillRequired = nil,
        resource = "Wool Cloth",
        description = "Orc camps in Redridge give excellent wool rates and straightforward pull patterns. Patrols can stack quickly, so work the camp edges before diving into central tents. Recommended level 20-26 for strong wool throughput and weapon vendor drops."
    },
    {
        id = "cloth_stonetalon_windshear_crag",
        name = "Stonetalon Windshear Crag",
        mapID = 1419,
        x = 0.600,
        y = 0.540,
        type = "FARM",
        category = "CLOTH",
        levelMin = 22,
        levelMax = 28,
        skillRequired = nil,
        resource = "Wool Cloth/Silk Cloth",
        description = "Venture Co. workers and nearby camps provide mixed wool and early silk drops. Vertical terrain makes route planning important, but mob density stays excellent across full loops. Farm here at level 22-28 to prepare for silk-heavy crafting needs."
    },
    {
        id = "cloth_hillsbrad_mine_workers",
        name = "Hillsbrad Mine Workers",
        mapID = 1424,
        x = 0.370,
        y = 0.600,
        type = "FARM",
        category = "CLOTH",
        levelMin = 24,
        levelMax = 30,
        skillRequired = nil,
        resource = "Wool Cloth/Silk Cloth",
        description = "The mine and field workers around Hillsbrad are classic humanoid cloth targets. Respawns are steady enough for continuous grinding without route breaks. Level 24-30 is ideal for pushing into a reliable silk stockpile."
    },
    {
        id = "cloth_duskwood_tranquil_gardens",
        name = "Duskwood Tranquil Gardens",
        mapID = 1431,
        x = 0.800,
        y = 0.360,
        type = "FARM",
        category = "CLOTH",
        levelMin = 26,
        levelMax = 32,
        skillRequired = nil,
        resource = "Silk Cloth",
        description = "Undead and humanoid packs around Tranquil Gardens drop silk at very dependable rates. Limited travel distance between pull pockets keeps your kill tempo high. Recommended level 26-32 for efficient silk farming in Eastern Kingdoms."
    },
    {
        id = "cloth_ashenvale_fallen_sky_lake",
        name = "Ashenvale Fallen Sky Lake",
        mapID = 1440,
        x = 0.660,
        y = 0.820,
        type = "FARM",
        category = "CLOTH",
        levelMin = 28,
        levelMax = 34,
        skillRequired = nil,
        resource = "Silk Cloth",
        description = "Satyrs and nearby camps in southern Ashenvale provide a strong silk farming rhythm. Pulling around the lake perimeter reduces downtime and avoids deep camp overpulls. Farm here at level 28-34 for stable silk and useful green drops."
    },
    {
        id = "cloth_stranglethorn_kurzen_camp",
        name = "Stranglethorn Kurzen Camp",
        mapID = 1434,
        x = 0.450,
        y = 0.090,
        type = "FARM",
        category = "CLOTH",
        levelMin = 30,
        levelMax = 36,
        skillRequired = nil,
        resource = "Silk Cloth",
        description = "Kurzen cave and terrace packs are a long-standing silk route in Classic Era. Spawns are dense and often chain perfectly for high kill uptime. Level 30-36 players can convert this camp into excellent silk-per-hour results."
    },
    {
        id = "cloth_arathi_boulderfist_camp",
        name = "Arathi Boulderfist Camp",
        mapID = 1417,
        x = 0.520,
        y = 0.740,
        type = "FARM",
        category = "CLOTH",
        levelMin = 32,
        levelMax = 38,
        skillRequired = nil,
        resource = "Silk Cloth/Mageweave Cloth",
        description = "Ogre camps in Arathi bridge late silk into early mageweave drops. The open camp layout supports efficient tagging and fast reset loops. Recommended level 32-38 for a smooth cloth bracket transition."
    },
    {
        id = "cloth_desolace_magram_village",
        name = "Desolace Magram Village",
        mapID = 1443,
        x = 0.700,
        y = 0.730,
        type = "FARM",
        category = "CLOTH",
        levelMin = 34,
        levelMax = 40,
        skillRequired = nil,
        resource = "Silk Cloth/Mageweave Cloth",
        description = "Centaur camps in southern Desolace provide dense humanoid pulls and cloth consistency. You can run broad circles between tent clusters to maintain constant combat flow. Farm at level 34-40 for dependable mixed cloth and coin."
    },
    {
        id = "cloth_badlands_rock_element_camp",
        name = "Badlands Rock Camp",
        mapID = 1418,
        x = 0.250,
        y = 0.450,
        type = "FARM",
        category = "CLOTH",
        levelMin = 36,
        levelMax = 42,
        skillRequired = nil,
        resource = "Mageweave Cloth",
        description = "Humanoid camps near the western Badlands roads drop steady mageweave with low travel time. The area is easy to path and has enough mobs for uninterrupted pulls. Level 36-42 characters can gather large mageweave stacks quickly here."
    },
    {
        id = "cloth_dustwallow_theramore_outskirts",
        name = "Dustwallow Theramore Outskirts",
        mapID = 1445,
        x = 0.630,
        y = 0.220,
        type = "FARM",
        category = "CLOTH",
        levelMin = 38,
        levelMax = 44,
        skillRequired = nil,
        resource = "Mageweave Cloth",
        description = "Outpost and shoreline humanoids around Theramore's edges are strong mageweave targets. Patrol routes are predictable, helping solo farmers avoid accidental chain pulls. Recommended level 38-44 for efficient mageweave gathering in Kalimdor."
    },
    {
        id = "cloth_tanaris_southsea_docks",
        name = "Tanaris Southsea Docks",
        mapID = 1446,
        x = 0.730,
        y = 0.460,
        type = "FARM",
        category = "CLOTH",
        levelMin = 40,
        levelMax = 46,
        skillRequired = nil,
        resource = "Mageweave Cloth",
        description = "Southsea pirates at the cove provide very fast respawns and excellent mageweave rates. Flat terrain and close mob spacing keep your pull chain smooth. Farm at level 40-46 for one of the strongest mid-game cloth spots."
    },
    {
        id = "cloth_feralas_ruins_of_isildien",
        name = "Feralas Ruins of Isildien",
        mapID = 1444,
        x = 0.600,
        y = 0.560,
        type = "FARM",
        category = "CLOTH",
        levelMin = 42,
        levelMax = 48,
        skillRequired = nil,
        resource = "Mageweave Cloth",
        description = "Ogre and warlock camps in Isildien create dense and lucrative mageweave farming loops. Pull carefully around casters to keep combat flow fast and controlled. Recommended level 42-48 for high cloth output and reliable green items."
    },
    {
        id = "cloth_hinterlands_troll_ruins",
        name = "Hinterlands Troll Ruins",
        mapID = 1425,
        x = 0.620,
        y = 0.690,
        type = "FARM",
        category = "CLOTH",
        levelMin = 44,
        levelMax = 50,
        skillRequired = nil,
        resource = "Mageweave Cloth",
        description = "Troll ruins in the Hinterlands offer compact camps with strong mageweave drop consistency. The route can be chained through multiple ruin clusters with little downtime. Level 44-50 players can farm here while building gold and reputation side gains."
    },
    {
        id = "cloth_blasted_lands_dreadmaul_hold",
        name = "Blasted Lands Dreadmaul Hold",
        mapID = 1439,
        x = 0.470,
        y = 0.150,
        type = "FARM",
        category = "CLOTH",
        levelMin = 46,
        levelMax = 52,
        skillRequired = nil,
        resource = "Mageweave Cloth/Runecloth",
        description = "The ogres of Dreadmaul Hold drop late mageweave with early runecloth crossover. Camp layout supports circular pulls that minimize dead time between fights. Farm at level 46-52 for a smooth shift toward endgame cloth markets."
    },
    {
        id = "cloth_felwood_jadefire_run",
        name = "Felwood Jadefire Run",
        mapID = 1448,
        x = 0.420,
        y = 0.570,
        type = "FARM",
        category = "CLOTH",
        levelMin = 48,
        levelMax = 54,
        skillRequired = nil,
        resource = "Runecloth",
        description = "Jadefire satyrs are among the most reliable runecloth targets before full endgame zones. Fast respawns and concentrated camp design make this a strong solo loop. Recommended level 48-54 for dependable runecloth and valuable demonic drops."
    },
    {
        id = "cloth_burning_steppes_blackrock_outposts",
        name = "Burning Steppes Blackrock Outposts",
        mapID = 1428,
        x = 0.650,
        y = 0.420,
        type = "FARM",
        category = "CLOTH",
        levelMin = 50,
        levelMax = 56,
        skillRequired = nil,
        resource = "Runecloth",
        description = "Blackrock humanoid camps across the steppes provide heavy runecloth rates and dense pulls. Casters can be dangerous, so pull them out of packs to maintain rhythm. Level 50-56 farmers can generate steady runecloth and vendor income here."
    },
    {
        id = "cloth_western_plaguelands_andorhal",
        name = "Western Plaguelands Andorhal",
        mapID = 1422,
        x = 0.450,
        y = 0.690,
        type = "FARM",
        category = "CLOTH",
        levelMin = 52,
        levelMax = 58,
        skillRequired = nil,
        resource = "Runecloth",
        description = "Andorhal's dense undead and humanoid presence enables nonstop runecloth farming loops. The city layout allows efficient routing through blocks with frequent respawns. Farm at level 52-58 for excellent runecloth stacks and extra scourgestone potential."
    },
    {
        id = "cloth_deadwind_ogre_ruins",
        name = "Deadwind Pass Ogre Ruins",
        mapID = 1430,
        x = 0.580,
        y = 0.730,
        type = "FARM",
        category = "CLOTH",
        levelMin = 53,
        levelMax = 58,
        skillRequired = nil,
        resource = "Runecloth",
        description = "Deadwind ogres provide dense high-level pulls and dependable runecloth drops in a compact area. The isolated zone often has lighter competition than other endgame cloth farms. Farm here at level 53-58 for efficient runecloth and steady vendor income."
    },
    {
        id = "cloth_azshara_legashi_satyrs",
        name = "Azshara Legashi Satyrs",
        mapID = 1447,
        x = 0.590,
        y = 0.780,
        type = "FARM",
        category = "CLOTH",
        levelMin = 54,
        levelMax = 60,
        skillRequired = nil,
        resource = "Runecloth/Felcloth",
        description = "Legashi camps are prized for runecloth consistency and rare felcloth opportunities. The area rewards careful pull control due to caster-heavy satyr packs. Recommended level 54-60 for high-value cloth farming in Classic Era."
    },
    {
        id = "cloth_eastern_plaguelands_terrordale",
        name = "Eastern Plaguelands Terrordale",
        mapID = 1423,
        x = 0.140,
        y = 0.680,
        type = "FARM",
        category = "CLOTH",
        levelMin = 55,
        levelMax = 60,
        skillRequired = nil,
        resource = "Runecloth",
        description = "Terrordale packs provide a dense runecloth route for geared players seeking endgame materials. Pull patterns are straightforward once you establish a clockwise camp rotation. Farm here at level 55-60 for excellent cloth volume and elite farming pace."
    },
    {
        id = "cloth_winterspring_frostsaber_post",
        name = "Winterspring Frostsaber Post",
        mapID = 1452,
        x = 0.620,
        y = 0.250,
        type = "FARM",
        category = "CLOTH",
        levelMin = 56,
        levelMax = 60,
        skillRequired = nil,
        resource = "Runecloth",
        description = "The high-level camps near Frostsaber areas provide strong runecloth returns with manageable travel. Visibility is excellent, letting you plan pull chains from a distance. Level 56-60 farmers can sustain steady runecloth income during long sessions."
    },
}
