EOA_DATA = EOA_DATA or {}

EOA_DATA.Dungeons = {
    {
        id = "dungeon_ragefire_chasm",
        name = "Ragefire Chasm",
        mapID = 1454,
        x = 0.520,
        y = 0.490,
        type = "DUNGEON",
        levelMin = 13,
        levelMax = 18,
        recommendedPlayers = 5,
        description = "A fiery cavern beneath Orgrimmar filled with hostile troggs and cultists."
    },
    {
        id = "dungeon_wailing_caverns",
        name = "Wailing Caverns",
        mapID = 1413,
        x = 0.460,
        y = 0.360,
        type = "DUNGEON",
        levelMin = 15,
        levelMax = 25,
        recommendedPlayers = 5,
        description = "A sprawling cave network in the Barrens corrupted by the Emerald Dream."
    },
    {
        id = "dungeon_deadmines",
        name = "The Deadmines",
        mapID = 1436,
        x = 0.420,
        y = 0.710,
        type = "DUNGEON",
        levelMin = 18,
        levelMax = 23,
        recommendedPlayers = 5,
        description = "A Defias-controlled mine and shipyard hidden beneath Westfall."
    },
    {
        id = "dungeon_shadowfang_keep",
        name = "Shadowfang Keep",
        mapID = 1421,
        x = 0.450,
        y = 0.680,
        type = "DUNGEON",
        levelMin = 22,
        levelMax = 30,
        recommendedPlayers = 5,
        description = "A haunted keep in Silverpine Forest ruled by undead and worgen."
    },
    {
        id = "dungeon_the_stockade",
        name = "The Stockade",
        mapID = 1453,
        x = 0.400,
        y = 0.550,
        type = "DUNGEON",
        levelMin = 22,
        levelMax = 30,
        recommendedPlayers = 5,
        description = "A prison dungeon beneath Stormwind overrun by dangerous inmates."
    },
    {
        id = "dungeon_blackfathom_deeps",
        name = "Blackfathom Deeps",
        mapID = 1440,
        x = 0.140,
        y = 0.140,
        type = "DUNGEON",
        levelMin = 24,
        levelMax = 32,
        recommendedPlayers = 5,
        description = "A flooded temple in Ashenvale occupied by naga and twilight forces."
    },
    {
        id = "dungeon_scarlet_monastery_graveyard",
        name = "Scarlet Monastery Graveyard",
        mapID = 1420,
        x = 0.830,
        y = 0.330,
        type = "DUNGEON",
        levelMin = 26,
        levelMax = 36,
        recommendedPlayers = 5,
        description = "The outer cemetery wing of Scarlet Monastery with undead patrols."
    },
    {
        id = "dungeon_gnomeregan",
        name = "Gnomeregan",
        mapID = 1426,
        x = 0.250,
        y = 0.380,
        type = "DUNGEON",
        levelMin = 29,
        levelMax = 38,
        recommendedPlayers = 5,
        description = "A mechanized gnome city overrun by troggs and radiation hazards."
    },
    {
        id = "dungeon_scarlet_monastery_library",
        name = "Scarlet Monastery Library",
        mapID = 1420,
        x = 0.830,
        y = 0.330,
        type = "DUNGEON",
        levelMin = 29,
        levelMax = 39,
        recommendedPlayers = 5,
        description = "The scholarly wing of Scarlet Monastery guarded by fanatical crusaders."
    },
    {
        id = "dungeon_razorfen_kraul",
        name = "Razorfen Kraul",
        mapID = 1413,
        x = 0.420,
        y = 0.900,
        type = "DUNGEON",
        levelMin = 30,
        levelMax = 40,
        recommendedPlayers = 5,
        description = "A thorned quilboar stronghold in the southern Barrens."
    },
    {
        id = "dungeon_scarlet_monastery_armory",
        name = "Scarlet Monastery Armory",
        mapID = 1420,
        x = 0.830,
        y = 0.330,
        type = "DUNGEON",
        levelMin = 32,
        levelMax = 42,
        recommendedPlayers = 5,
        description = "A heavily defended Scarlet armory led by elite crusade commanders."
    },
    {
        id = "dungeon_scarlet_monastery_cathedral",
        name = "Scarlet Monastery Cathedral",
        mapID = 1420,
        x = 0.830,
        y = 0.330,
        type = "DUNGEON",
        levelMin = 35,
        levelMax = 45,
        recommendedPlayers = 5,
        description = "The grand cathedral wing housing Scarlet Monastery's high command."
    },
    {
        id = "dungeon_razorfen_downs",
        name = "Razorfen Downs",
        mapID = 1413,
        x = 0.500,
        y = 0.920,
        type = "DUNGEON",
        levelMin = 40,
        levelMax = 50,
        recommendedPlayers = 5,
        description = "A haunted quilboar necropolis with undead and shadow magic."
    },
    {
        id = "dungeon_uldaman",
        name = "Uldaman",
        mapID = 1418,
        x = 0.440,
        y = 0.120,
        type = "DUNGEON",
        levelMin = 42,
        levelMax = 52,
        recommendedPlayers = 5,
        description = "An ancient titan vault in the Badlands full of constructs and relics."
    },
    {
        id = "dungeon_zulfarrak",
        name = "Zul'Farrak",
        mapID = 1446,
        x = 0.390,
        y = 0.210,
        type = "DUNGEON",
        levelMin = 44,
        levelMax = 54,
        recommendedPlayers = 5,
        description = "A troll city in Tanaris known for brutal sandfury rituals."
    },
    {
        id = "dungeon_maraudon",
        name = "Maraudon",
        mapID = 1443,
        x = 0.290,
        y = 0.620,
        type = "DUNGEON",
        levelMin = 46,
        levelMax = 55,
        recommendedPlayers = 5,
        description = "A vast desolace cavern split into corrupted and pristine elemental wings."
    },
    {
        id = "dungeon_sunken_temple",
        name = "Temple of Atal'Hakkar",
        mapID = 1435,
        x = 0.700,
        y = 0.530,
        type = "DUNGEON",
        levelMin = 50,
        levelMax = 60,
        recommendedPlayers = 5,
        description = "A submerged troll temple in the Swamp of Sorrows devoted to Hakkar."
    },
    {
        id = "dungeon_blackrock_depths",
        name = "Blackrock Depths",
        mapID = 1428,
        x = 0.340,
        y = 0.850,
        type = "DUNGEON",
        levelMin = 52,
        levelMax = 60,
        recommendedPlayers = 5,
        description = "A massive Dark Iron city-dungeon deep within Blackrock Mountain."
    },
    {
        id = "dungeon_lower_blackrock_spire",
        name = "Lower Blackrock Spire",
        mapID = 1428,
        x = 0.330,
        y = 0.840,
        type = "DUNGEON",
        levelMin = 55,
        levelMax = 60,
        recommendedPlayers = 5,
        description = "The lower halls of Blackrock Spire occupied by orcs and war beasts."
    },
    {
        id = "dungeon_upper_blackrock_spire",
        name = "Upper Blackrock Spire",
        mapID = 1428,
        x = 0.330,
        y = 0.840,
        type = "DUNGEON",
        levelMin = 55,
        levelMax = 60,
        recommendedPlayers = 5,
        description = "The upper fortress of Blackrock Spire leading to General Drakkisath."
    },
    {
        id = "dungeon_dire_maul_east",
        name = "Dire Maul East",
        mapID = 1444,
        x = 0.640,
        y = 0.300,
        type = "DUNGEON",
        levelMin = 55,
        levelMax = 60,
        recommendedPlayers = 5,
        description = "The warped eastern wing of Dire Maul filled with satyrs and elementals."
    },
    {
        id = "dungeon_dire_maul_west",
        name = "Dire Maul West",
        mapID = 1444,
        x = 0.620,
        y = 0.240,
        type = "DUNGEON",
        levelMin = 55,
        levelMax = 60,
        recommendedPlayers = 5,
        description = "The haunted western halls of Dire Maul with arcane and spectral foes."
    },
    {
        id = "dungeon_dire_maul_north",
        name = "Dire Maul North",
        mapID = 1444,
        x = 0.600,
        y = 0.240,
        type = "DUNGEON",
        levelMin = 55,
        levelMax = 60,
        recommendedPlayers = 5,
        description = "The ogre-held northern district of Dire Maul known as Gordok Commons."
    },
    {
        id = "dungeon_scholomance",
        name = "Scholomance",
        mapID = 1422,
        x = 0.700,
        y = 0.730,
        type = "DUNGEON",
        levelMin = 58,
        levelMax = 60,
        recommendedPlayers = 5,
        description = "A necromantic academy in Western Plaguelands teeming with undead."
    },
    {
        id = "dungeon_stratholme_live",
        name = "Stratholme (Live)",
        mapID = 1423,
        x = 0.300,
        y = 0.120,
        type = "DUNGEON",
        levelMin = 58,
        levelMax = 60,
        recommendedPlayers = 5,
        description = "The Scarlet side of Stratholme with crusaders and living defenders."
    },
    {
        id = "dungeon_stratholme_undead",
        name = "Stratholme (Undead)",
        mapID = 1423,
        x = 0.300,
        y = 0.120,
        type = "DUNGEON",
        levelMin = 58,
        levelMax = 60,
        recommendedPlayers = 5,
        description = "The undead quarter of Stratholme ruled by abominations and banshees."
    },
}
