-- EOA_Data_Utility.lua
EOA_DATA = EOA_DATA or {}

EOA_DATA.Utility = {
    {
        id = "utility_boat_menethil_auberdine",
        name = "Boat: Menethil Harbor",
        mapID = 1437,
        x = 0.070,
        y = 0.565,
        type = "UTILITY",
        levelMin = nil,
        levelMax = nil,
        profession = nil,
        resource = "Boat",
        tags = { "transport", "alliance", "kalimdor-link" },
        description = "Primary Menethil Harbor dock with routes to Kalimdor ports."
    },
    {
        id = "utility_boat_theramore_menethil",
        name = "Boat: Theramore Isle",
        mapID = 1445,
        x = 0.675,
        y = 0.510,
        type = "UTILITY",
        levelMin = nil,
        levelMax = nil,
        profession = nil,
        resource = "Boat",
        tags = { "transport", "alliance", "eastern-kingdoms-link" },
        description = "Theramore dock for Eastern Kingdoms travel access."
    },
    {
        id = "utility_zeppelin_orgrimmar",
        name = "Zeppelin: Orgrimmar Tower",
        mapID = 1411,
        x = 0.507,
        y = 0.130,
        type = "UTILITY",
        levelMin = nil,
        levelMax = nil,
        profession = nil,
        resource = "Zeppelin",
        tags = { "transport", "horde", "tower" },
        description = "Orgrimmar zeppelin tower connecting to major Horde transit routes."
    },
    {
        id = "utility_zeppelin_tirisfal",
        name = "Zeppelin: Tirisfal Glades",
        mapID = 1420,
        x = 0.605,
        y = 0.590,
        type = "UTILITY",
        levelMin = nil,
        levelMax = nil,
        profession = nil,
        resource = "Zeppelin",
        tags = { "transport", "horde", "undercity" },
        description = "Tirisfal zeppelin tower servicing northern Horde travel."
    },
    {
        id = "utility_worldbuff_rend",
        name = "World Buff: Rend Turn-in (Orgrimmar)",
        mapID = 1454,
        x = 0.810,
        y = 0.180,
        type = "UTILITY",
        levelMin = 55,
        levelMax = 60,
        profession = nil,
        resource = "World Buff",
        tags = { "world-buff", "horde", "raid-prep" },
        description = "Warchief's Blessing trigger area for Onyxia/Nefarian head turn-ins."
    },
    {
        id = "utility_worldbuff_ony_stormwind",
        name = "World Buff: Stormwind Keep",
        mapID = 1453,
        x = 0.800,
        y = 0.380,
        type = "UTILITY",
        levelMin = 55,
        levelMax = 60,
        profession = nil,
        resource = "World Buff",
        tags = { "world-buff", "alliance", "raid-prep" },
        description = "Rallying Cry turn-in area in Stormwind Keep for raid preparation."
    },
    {
        id = "utility_meeting_stone_sm",
        name = "Meeting Stone: Scarlet Monastery",
        mapID = 1420,
        x = 0.835,
        y = 0.340,
        type = "UTILITY",
        levelMin = 26,
        levelMax = 45,
        profession = nil,
        resource = "Meeting Stone",
        tags = { "meeting-stone", "instance", "grouping" },
        description = "Group assembly point outside Scarlet Monastery courtyard."
    },
    {
        id = "utility_meeting_stone_brd",
        name = "Meeting Stone: Blackrock Depths",
        mapID = 1428,
        x = 0.350,
        y = 0.845,
        type = "UTILITY",
        levelMin = 52,
        levelMax = 60,
        profession = nil,
        resource = "Meeting Stone",
        tags = { "meeting-stone", "instance", "endgame" },
        description = "Common BRD/Blackrock Mountain group-up location at chain approach."
    },
}
