-- EOA_Data_Mining.lua
EOA_DATA = EOA_DATA or {}

EOA_DATA.Mining = {
    {
        id = "mining_durotar_ridge_spine",
        name = "Durotar Ridge Spine",
        mapID = 1411,
        x = 0.520,
        y = 0.430,
        type = "FARM",
        category = "MINING",
        levelMin = 8,
        levelMax = 14,
        skillRequired = 1,
        resource = "Copper Vein",
        description = "This beginner loop follows the rocky ridges between Razor Hill and Orgrimmar where copper nodes appear in plain sight. Hostile packs are light, so new miners can focus on learning efficient node-to-node movement. Run the route at level 8-14 for steady copper and rough stone while building your first profession ranks."
    },
    {
        id = "mining_dun_morogh_valley_ring",
        name = "Dun Morogh Valley Ring",
        mapID = 1426,
        x = 0.470,
        y = 0.520,
        type = "FARM",
        category = "MINING",
        levelMin = 8,
        levelMax = 14,
        skillRequired = 1,
        resource = "Copper Vein",
        description = "Circle the snowy foothills around Kharanos and Anvilmar for a very safe copper route. Caves add extra node density if you can clear troggs quickly between pulls. Recommended for level 8-14 miners who want stable copper without long travel gaps."
    },
    {
        id = "mining_elwynn_stonefield_pass",
        name = "Elwynn Stonefield Pass",
        mapID = 1429,
        x = 0.420,
        y = 0.670,
        type = "FARM",
        category = "MINING",
        levelMin = 10,
        levelMax = 16,
        skillRequired = 1,
        resource = "Copper Vein",
        description = "Work the hills near Jasperlode Mine and the Stonefield farm edges for beginner copper spawns. The terrain is gentle, making this route easy for characters with no movement tools. Farm here at level 10-16 to stock copper bars and coarse stone for early crafting."
    },
    {
        id = "mining_darkshore_cliff_run",
        name = "Darkshore Cliff Run",
        mapID = 1439,
        x = 0.430,
        y = 0.360,
        type = "FARM",
        category = "MINING",
        levelMin = 12,
        levelMax = 18,
        skillRequired = 1,
        resource = "Copper Vein/Tin Vein",
        description = "Darkshore cliffs give a mixed copper and tin path with many nodes tucked against rock walls. Murloc pressure is manageable if you stay on higher ground and avoid beach overpulls. This is a strong level 12-18 transition route while raising Mining toward Journeyman goals."
    },
    {
        id = "mining_loch_modan_quarry_loop",
        name = "Loch Modan Quarry Loop",
        mapID = 1432,
        x = 0.350,
        y = 0.220,
        type = "FARM",
        category = "MINING",
        levelMin = 14,
        levelMax = 22,
        skillRequired = 65,
        resource = "Tin Vein",
        description = "Patrol around Silver Stream Mine and quarry ridges for dependable tin with occasional copper leftovers. Kobold caves concentrate veins but require careful pulls if your gear is weak. Level 14-22 characters can keep this loop flowing with short reset times between node spawns."
    },
    {
        id = "mining_barrens_north_approach",
        name = "Northern Barrens Approach",
        mapID = 1413,
        x = 0.510,
        y = 0.260,
        type = "FARM",
        category = "MINING",
        levelMin = 16,
        levelMax = 24,
        skillRequired = 65,
        resource = "Tin Vein",
        description = "This long route from the Dry Hills to the Sludge Fen catches tin along exposed rock lines. Competition can be high, so keep moving and prioritize cave entrances for hidden nodes. Recommended for level 16-24 farmers building a large supply of tin and medium stone."
    },
    {
        id = "mining_westfall_ridge_circuit",
        name = "Westfall Ridge Circuit",
        mapID = 1436,
        x = 0.520,
        y = 0.300,
        type = "FARM",
        category = "MINING",
        levelMin = 16,
        levelMax = 24,
        skillRequired = 65,
        resource = "Tin Vein",
        description = "Run the inland ridges and mine edges where Defias camps sit near stone outcrops. Westfall offers easy navigation and frequent return paths to town for smelting. Level 16-24 is ideal for this circuit before stepping into heavier contested zones."
    },
    {
        id = "mining_redridge_lake_hills",
        name = "Redridge Lake Hills",
        mapID = 1433,
        x = 0.370,
        y = 0.590,
        type = "FARM",
        category = "MINING",
        levelMin = 18,
        levelMax = 26,
        skillRequired = 65,
        resource = "Tin Vein/Silver Vein",
        description = "Mine the eastern hills and cave pockets for tin with occasional silver upgrades. Gnoll camps can interrupt the route, so clear smartly and keep your path clockwise around spawn hotspots. Farm at level 18-26 for solid ore variety and smooth profession gains."
    },
    {
        id = "mining_stonetalon_charred_vale",
        name = "Stonetalon Charred Vale",
        mapID = 1419,
        x = 0.340,
        y = 0.680,
        type = "FARM",
        category = "MINING",
        levelMin = 20,
        levelMax = 28,
        skillRequired = 65,
        resource = "Tin Vein/Iron Deposit",
        description = "Charred Vale edges blend late tin and early iron nodes in a compact mountain pocket. Harpies and elementals require caution, but the node density rewards efficient clearing. Level 20-28 miners can bridge into iron farming without changing continents."
    },
    {
        id = "mining_hillsbrad_mine_sweep",
        name = "Hillsbrad Mine Sweep",
        mapID = 1424,
        x = 0.490,
        y = 0.420,
        type = "FARM",
        category = "MINING",
        levelMin = 22,
        levelMax = 30,
        skillRequired = 125,
        resource = "Iron Deposit",
        description = "Work the Yeti Cave rim and mountain cuts north of Tarren Mill for consistent iron. The area has fast respawns of humanoids, so choose off-hours if you want uninterrupted loops. Recommended level 22-30 for players converting to heavy iron routes."
    },
    {
        id = "mining_ashenvale_stardust_peaks",
        name = "Ashenvale Stardust Peaks",
        mapID = 1440,
        x = 0.330,
        y = 0.330,
        type = "FARM",
        category = "MINING",
        levelMin = 24,
        levelMax = 32,
        skillRequired = 125,
        resource = "Iron Deposit",
        description = "The ridges near Stardust Spire contain iron nodes hidden behind trees and ruins. Route efficiency improves if you chain both mountain sides instead of waiting for local respawns. This level 24-32 path provides reliable iron for Blacksmithing and Engineering demand."
    },
    {
        id = "mining_thousand_needles_highpath",
        name = "Thousand Needles Highpath",
        mapID = 1441,
        x = 0.110,
        y = 0.180,
        type = "FARM",
        category = "MINING",
        levelMin = 26,
        levelMax = 34,
        skillRequired = 125,
        resource = "Iron Deposit",
        description = "Run the Great Lift approaches and canyon walls for iron nodes in narrow but efficient lines. The vertical terrain is dangerous, so plan a full circuit before dropping into side canyons. Farm here at level 26-34 to maintain strong iron-per-hour in Classic Era."
    },
    {
        id = "mining_alterac_foothills_stonespine",
        name = "Alterac Stonespine Route",
        mapID = 1416,
        x = 0.420,
        y = 0.730,
        type = "FARM",
        category = "MINING",
        levelMin = 28,
        levelMax = 36,
        skillRequired = 125,
        resource = "Iron Deposit/Gold Vein",
        description = "Follow the broken mountain spine for iron with occasional gold nodes in less traveled alcoves. Syndicate mobs are dense, but their humanoid loot offsets downtime between mining pulls. Level 28-36 farmers will find this route efficient for ore and coin together."
    },
    {
        id = "mining_stranglethorn_north_rim",
        name = "Stranglethorn North Rim",
        mapID = 1434,
        x = 0.430,
        y = 0.230,
        type = "FARM",
        category = "MINING",
        levelMin = 30,
        levelMax = 38,
        skillRequired = 125,
        resource = "Iron Deposit",
        description = "The northern jungle rim offers iron nodes along cliffs above the main roads. Keep pulls controlled because beast packs can chain quickly in dense foliage. Recommended for level 30-38 miners wanting iron while leveling through Stranglethorn quests."
    },
    {
        id = "mining_arathi_boulderfall",
        name = "Arathi Boulderfall Loop",
        mapID = 1417,
        x = 0.660,
        y = 0.320,
        type = "FARM",
        category = "MINING",
        levelMin = 32,
        levelMax = 40,
        skillRequired = 150,
        resource = "Mithril Deposit",
        description = "Boulderfist and cave-adjacent ridges spawn early mithril with occasional iron cleanup nodes. Arathi is open terrain, making it easy to chain a large circular path with little backtracking. Level 32-40 is the sweet spot for entering mithril production comfortably."
    },
    {
        id = "mining_desolace_kodo_bone_run",
        name = "Desolace Kodo Bone Run",
        mapID = 1443,
        x = 0.560,
        y = 0.510,
        type = "FARM",
        category = "MINING",
        levelMin = 34,
        levelMax = 42,
        skillRequired = 150,
        resource = "Mithril Deposit",
        description = "Sweep from Kodo Graveyard to valley walls where mithril spawns along pale cliffs. Mob density is moderate, allowing long stretches of uninterrupted gathering. Level 34-42 miners can sustain good mithril intake with simple clockwise loops."
    },
    {
        id = "mining_badlands_western_sweep",
        name = "Badlands Western Sweep",
        mapID = 1418,
        x = 0.190,
        y = 0.560,
        type = "FARM",
        category = "MINING",
        levelMin = 36,
        levelMax = 44,
        skillRequired = 150,
        resource = "Mithril Deposit",
        description = "Badlands remains one of the classic mithril zones thanks to rich canyon wall spawns. The route is straightforward and scales well for solo players with limited travel tools. Recommended level 36-44 for stable mithril and heavy stone output."
    },
    {
        id = "mining_tanaris_dune_veins",
        name = "Tanaris Dune Veins",
        mapID = 1446,
        x = 0.510,
        y = 0.290,
        type = "FARM",
        category = "MINING",
        levelMin = 40,
        levelMax = 48,
        skillRequired = 175,
        resource = "Mithril Deposit/Truesilver Deposit",
        description = "Mine the dune ridges and inland cliffs around Gadgetzan for steady mithril and rare truesilver. The open desert makes route planning simple and minimizes accidental multi-pulls. Level 40-48 farmers can keep a clean lap cycle with very little downtime."
    },
    {
        id = "mining_feralas_twin_colossals",
        name = "Feralas Twin Colossals Route",
        mapID = 1444,
        x = 0.470,
        y = 0.410,
        type = "FARM",
        category = "MINING",
        levelMin = 42,
        levelMax = 50,
        skillRequired = 175,
        resource = "Mithril Deposit/Truesilver Deposit",
        description = "Path between mountain boundaries near the Twin Colossals and cave mouths for mithril clusters. The route benefits classes that can move quickly through dense foliage and uneven terrain. Farm at level 42-50 to prepare for thorium-tier transitions later."
    },
    {
        id = "mining_searing_gorge_outer_ring",
        name = "Searing Gorge Outer Ring",
        mapID = 1427,
        x = 0.420,
        y = 0.350,
        type = "FARM",
        category = "MINING",
        levelMin = 45,
        levelMax = 53,
        skillRequired = 175,
        resource = "Mithril Deposit/Thorium Vein",
        description = "Run the outer volcanic walls where mithril and small thorium veins alternate in dense pockets. Fire mobs are aggressive, so movement discipline is important for uninterrupted mining laps. This level 45-53 route is a proven Classic Era staple for ore progression."
    },
    {
        id = "mining_felwood_irontree_path",
        name = "Felwood Irontree Path",
        mapID = 1448,
        x = 0.540,
        y = 0.210,
        type = "FARM",
        category = "MINING",
        levelMin = 47,
        levelMax = 55,
        skillRequired = 175,
        resource = "Mithril Deposit/Thorium Vein",
        description = "Irontree woods and corrupted clearings hide veins along both central and eastern walls. Expect satyr pressure near chokepoints, but node rewards stay strong through long sessions. Recommended for level 47-55 miners building thorium stock before endgame zones."
    },
    {
        id = "mining_burning_steppes_ridge_route",
        name = "Burning Steppes Ridge Route",
        mapID = 1428,
        x = 0.620,
        y = 0.370,
        type = "FARM",
        category = "MINING",
        levelMin = 50,
        levelMax = 58,
        skillRequired = 230,
        resource = "Thorium Vein",
        description = "This ridge-to-ridge route gives excellent small thorium uptime with occasional rich upgrades. Dragonkin patrols demand careful pulls, especially near narrow ledges and cave entries. Level 50-58 characters can sustain high ore-per-hour with disciplined circuit timing."
    },
    {
        id = "mining_ungoro_wall_circuit",
        name = "Un'Goro Wall Circuit",
        mapID = 1449,
        x = 0.490,
        y = 0.550,
        type = "FARM",
        category = "MINING",
        levelMin = 52,
        levelMax = 60,
        skillRequired = 230,
        resource = "Thorium Vein/Rich Thorium Vein",
        description = "Follow Un'Goro's crater walls and cave entrances for one of the most famous thorium paths in Classic Era. Elementals and elites can slow newer characters, so use wide turns and avoid overcommitting in caves. Farm here from level 52-60 for steady thorium and arcane crystal chances."
    },
    {
        id = "mining_western_plaguelands_northwall",
        name = "Western Plaguelands Northwall",
        mapID = 1422,
        x = 0.440,
        y = 0.180,
        type = "FARM",
        category = "MINING",
        levelMin = 54,
        levelMax = 60,
        skillRequired = 230,
        resource = "Thorium Vein",
        description = "Northern ruins and hillside paths provide consistent thorium with moderate competition. Undead clusters are dense but predictable, letting experienced players weave mining and grind pulls together. Level 54-60 miners can keep profitable laps while farming additional scourge loot."
    },
    {
        id = "mining_winterspring_ice_thistle_loop",
        name = "Winterspring Ice Thistle Loop",
        mapID = 1452,
        x = 0.610,
        y = 0.420,
        type = "FARM",
        category = "MINING",
        levelMin = 55,
        levelMax = 60,
        skillRequired = 245,
        resource = "Rich Thorium Vein",
        description = "The snowy perimeter and high ridges of Winterspring host premium rich thorium nodes. Long sightlines let you plan efficient route adjustments whenever contested nodes are missing. Recommended level 55-60 for endgame thorium farming and top-tier mining profits."
    },
}
