-- EOA_Data_DungeonsAndRaids.lua
EOA_DATA = EOA_DATA or {}

EOA_DATA.DungeonsAndRaids = {
    {
        id = "dungeon_ragefire_chasm",
        name = "Ragefire Chasm",
        mapID = 1454,
        x = 0.521,
        y = 0.486,
        type = "DUNGEON",
        levelMin = 13,
        levelMax = 18,
        recommendedPlayers = 5,
        tags = { "dungeon", "classic" },
        description = "Beneath Orgrimmar, this fiery cave is a quick early Horde dungeon run."
    },
    {
        id = "dungeon_wailing_caverns",
        name = "Wailing Caverns",
        mapID = 1413,
        x = 0.462,
        y = 0.362,
        type = "DUNGEON",
        levelMin = 15,
        levelMax = 25,
        recommendedPlayers = 5,
        tags = { "dungeon", "classic" },
        description = "A twisting cavern in the Barrens filled with druids, serpents, and long corridors."
    },
    {
        id = "dungeon_deadmines",
        name = "The Deadmines",
        mapID = 1436,
        x = 0.424,
        y = 0.710,
        type = "DUNGEON",
        levelMin = 18,
        levelMax = 23,
        recommendedPlayers = 5,
        tags = { "dungeon", "classic" },
        description = "A Defias stronghold beneath Westfall with iconic shipyard and pirate encounters."
    },
    {
        id = "dungeon_shadowfang_keep",
        name = "Shadowfang Keep",
        mapID = 1421,
        x = 0.451,
        y = 0.680,
        type = "DUNGEON",
        levelMin = 22,
        levelMax = 30,
        recommendedPlayers = 5,
        tags = { "dungeon", "classic" },
        description = "A haunted keep in Silverpine with undead foes and classic caster loot."
    },
    {
        id = "dungeon_the_stockade",
        name = "The Stockade",
        mapID = 1453,
        x = 0.407,
        y = 0.550,
        type = "DUNGEON",
        levelMin = 22,
        levelMax = 30,
        recommendedPlayers = 5,
        tags = { "dungeon", "classic" },
        description = "Stormwind's prison dungeon offering compact pulls and quick boss clears."
    },
    {
        id = "dungeon_blackfathom_deeps",
        name = "Blackfathom Deeps",
        mapID = 1440,
        x = 0.142,
        y = 0.138,
        type = "DUNGEON",
        levelMin = 24,
        levelMax = 32,
        recommendedPlayers = 5,
        tags = { "dungeon", "classic" },
        description = "An ancient night elf temple beneath the coast of Ashenvale."
    },
    {
        id = "dungeon_gnomeregan",
        name = "Gnomeregan",
        mapID = 1426,
        x = 0.243,
        y = 0.396,
        type = "DUNGEON",
        levelMin = 29,
        levelMax = 38,
        recommendedPlayers = 5,
        tags = { "dungeon", "classic" },
        description = "A sprawling irradiated city with mechanical enemies and tricky layouts."
    },
    {
        id = "dungeon_razorfen_kraul",
        name = "Razorfen Kraul",
        mapID = 1413,
        x = 0.427,
        y = 0.892,
        type = "DUNGEON",
        levelMin = 30,
        levelMax = 40,
        recommendedPlayers = 5,
        tags = { "dungeon", "classic" },
        description = "A quilboar fortress in the southern Barrens with thorny tunnels and elites."
    },
    {
        id = "dungeon_scarlet_monastery_graveyard",
        name = "Scarlet Monastery - Graveyard",
        mapID = 1420,
        x = 0.835,
        y = 0.330,
        type = "DUNGEON",
        levelMin = 26,
        levelMax = 45,
        recommendedPlayers = 5,
        tags = { "dungeon", "classic" },
        description = "The graveyard wing of Scarlet Monastery, favored for early wing farming."
    },
    {
        id = "dungeon_scarlet_monastery_library",
        name = "Scarlet Monastery - Library",
        mapID = 1420,
        x = 0.835,
        y = 0.330,
        type = "DUNGEON",
        levelMin = 26,
        levelMax = 45,
        recommendedPlayers = 5,
        tags = { "dungeon", "classic" },
        description = "The library wing with caster gear, Arcanist Doan, and dense humanoid packs."
    },
    {
        id = "dungeon_scarlet_monastery_armory",
        name = "Scarlet Monastery - Armory",
        mapID = 1420,
        x = 0.835,
        y = 0.330,
        type = "DUNGEON",
        levelMin = 26,
        levelMax = 45,
        recommendedPlayers = 5,
        tags = { "dungeon", "classic" },
        description = "The armory wing featuring Herod and strong melee-oriented rewards."
    },
    {
        id = "dungeon_scarlet_monastery_cathedral",
        name = "Scarlet Monastery - Cathedral",
        mapID = 1420,
        x = 0.835,
        y = 0.330,
        type = "DUNGEON",
        levelMin = 26,
        levelMax = 45,
        recommendedPlayers = 5,
        tags = { "dungeon", "classic" },
        description = "The cathedral wing with High Inquisitor Whitemane and Scarlet Commander Mograine."
    },
    {
        id = "dungeon_razorfen_downs",
        name = "Razorfen Downs",
        mapID = 1413,
        x = 0.502,
        y = 0.931,
        type = "DUNGEON",
        levelMin = 40,
        levelMax = 50,
        recommendedPlayers = 5,
        tags = { "dungeon", "classic" },
        description = "A haunted quilboar necropolis with undead-heavy trash and bosses."
    },
    {
        id = "dungeon_uldaman",
        name = "Uldaman",
        mapID = 1418,
        x = 0.445,
        y = 0.120,
        type = "DUNGEON",
        levelMin = 42,
        levelMax = 52,
        recommendedPlayers = 5,
        tags = { "dungeon", "classic" },
        description = "A titan ruin in the Badlands known for long quest chains and relic lore."
    },
    {
        id = "dungeon_zulfarrak",
        name = "Zul'Farrak",
        mapID = 1446,
        x = 0.391,
        y = 0.209,
        type = "DUNGEON",
        levelMin = 44,
        levelMax = 54,
        recommendedPlayers = 5,
        tags = { "dungeon", "classic" },
        description = "A troll city in Tanaris featuring stair events and outdoor-style paths."
    },
    {
        id = "dungeon_maraudon",
        name = "Maraudon",
        mapID = 1443,
        x = 0.297,
        y = 0.622,
        type = "DUNGEON",
        levelMin = 46,
        levelMax = 55,
        recommendedPlayers = 5,
        tags = { "dungeon", "classic" },
        description = "A vast cavern complex in Desolace split into orange and purple sections."
    },
    {
        id = "dungeon_sunken_temple",
        name = "Temple of Atal'Hakkar",
        mapID = 1435,
        x = 0.693,
        y = 0.537,
        type = "DUNGEON",
        levelMin = 50,
        levelMax = 60,
        recommendedPlayers = 5,
        tags = { "dungeon", "classic" },
        description = "The Sunken Temple in Swamp of Sorrows with dragonkin and troll rituals."
    },
    {
        id = "dungeon_blackrock_depths",
        name = "Blackrock Depths",
        mapID = 1428,
        x = 0.345,
        y = 0.845,
        type = "DUNGEON",
        levelMin = 52,
        levelMax = 60,
        recommendedPlayers = 5,
        tags = { "dungeon", "classic" },
        description = "A massive Dark Iron city-dungeon with many bosses and key questlines."
    },
    {
        id = "dungeon_lower_blackrock_spire",
        name = "Lower Blackrock Spire",
        mapID = 1428,
        x = 0.345,
        y = 0.845,
        type = "DUNGEON",
        levelMin = 55,
        levelMax = 60,
        recommendedPlayers = 10,
        tags = { "dungeon", "classic" },
        description = "The lower sections of Blackrock Spire with long pulls and faction content."
    },
    {
        id = "dungeon_upper_blackrock_spire",
        name = "Upper Blackrock Spire",
        mapID = 1428,
        x = 0.345,
        y = 0.845,
        type = "DUNGEON",
        levelMin = 55,
        levelMax = 60,
        recommendedPlayers = 10,
        tags = { "dungeon", "classic" },
        description = "A 10-player endgame dungeon route featuring Rend and General Drakkisath."
    },
    {
        id = "dungeon_dire_maul_east",
        name = "Dire Maul - East",
        mapID = 1444,
        x = 0.600,
        y = 0.452,
        type = "DUNGEON",
        levelMin = 55,
        levelMax = 60,
        recommendedPlayers = 5,
        tags = { "dungeon", "classic" },
        description = "The east wing of Dire Maul with warpwood and satyr-heavy encounters."
    },
    {
        id = "dungeon_dire_maul_west",
        name = "Dire Maul - West",
        mapID = 1444,
        x = 0.600,
        y = 0.452,
        type = "DUNGEON",
        levelMin = 55,
        levelMax = 60,
        recommendedPlayers = 5,
        tags = { "dungeon", "classic" },
        description = "The west wing with arcane constructs, ghosts, and class book drops."
    },
    {
        id = "dungeon_dire_maul_north",
        name = "Dire Maul - North",
        mapID = 1444,
        x = 0.600,
        y = 0.452,
        type = "DUNGEON",
        levelMin = 55,
        levelMax = 60,
        recommendedPlayers = 5,
        tags = { "dungeon", "classic" },
        description = "The north wing known for tribute runs and high-value endgame loot."
    },
    {
        id = "dungeon_scholomance",
        name = "Scholomance",
        mapID = 1422,
        x = 0.698,
        y = 0.732,
        type = "DUNGEON",
        levelMin = 58,
        levelMax = 60,
        recommendedPlayers = 5,
        tags = { "dungeon", "classic" },
        description = "A dark necromancer academy in Caer Darrow packed with undead enemies."
    },
    {
        id = "dungeon_stratholme_live",
        name = "Stratholme - Live Side",
        mapID = 1415,
        x = 0.304,
        y = 0.159,
        type = "DUNGEON",
        levelMin = 58,
        levelMax = 60,
        recommendedPlayers = 5,
        tags = { "dungeon", "classic" },
        description = "The Scarlet-heavy entrance wing of Stratholme in Eastern Plaguelands."
    },
    {
        id = "dungeon_stratholme_undead",
        name = "Stratholme - Undead Side",
        mapID = 1415,
        x = 0.304,
        y = 0.159,
        type = "DUNGEON",
        levelMin = 58,
        levelMax = 60,
        recommendedPlayers = 5,
        tags = { "dungeon", "classic" },
        description = "The undead wing leading toward Baron Rivendare and endgame pre-raid gear."
    },
    {
        id = "raid_onyxias_lair",
        name = "Onyxia's Lair",
        mapID = 1445,
        x = 0.525,
        y = 0.760,
        type = "RAID",
        levelMin = 60,
        levelMax = 60,
        recommendedPlayers = 40,
        tags = { "raid", "classic" },
        description = "A single-boss dragon raid in Dustwallow Marsh requiring attunement."
    },
    {
        id = "raid_molten_core",
        name = "Molten Core",
        mapID = 1428,
        x = 0.290,
        y = 0.385,
        type = "RAID",
        levelMin = 60,
        levelMax = 60,
        recommendedPlayers = 40,
        tags = { "raid", "classic" },
        description = "A deep Blackrock raid against Ragnaros and the Firelord's lieutenants."
    },
    {
        id = "raid_blackwing_lair",
        name = "Blackwing Lair",
        mapID = 1428,
        x = 0.306,
        y = 0.380,
        type = "RAID",
        levelMin = 60,
        levelMax = 60,
        recommendedPlayers = 40,
        tags = { "raid", "classic" },
        description = "Nefarian's fortress raid atop Blackrock Mountain with draconic bosses."
    },
    {
        id = "raid_zulgurub",
        name = "Zul'Gurub",
        mapID = 1434,
        x = 0.540,
        y = 0.175,
        type = "RAID",
        levelMin = 60,
        levelMax = 60,
        recommendedPlayers = 20,
        tags = { "raid", "classic" },
        description = "A 20-player troll raid in Stranglethorn Vale with jungle temple encounters."
    },
    {
        id = "raid_ruins_of_ahnqiraj",
        name = "Ruins of Ahn'Qiraj",
        mapID = 1451,
        x = 0.293,
        y = 0.922,
        type = "RAID",
        levelMin = 60,
        levelMax = 60,
        recommendedPlayers = 20,
        tags = { "raid", "classic" },
        description = "AQ20 is a 20-player raid focused on silithid and qiraji battles in Silithus."
    },
    {
        id = "raid_temple_of_ahnqiraj",
        name = "Temple of Ahn'Qiraj",
        mapID = 1451,
        x = 0.293,
        y = 0.922,
        type = "RAID",
        levelMin = 60,
        levelMax = 60,
        recommendedPlayers = 40,
        tags = { "raid", "classic" },
        description = "AQ40 is a 40-player raid featuring C'Thun and large-scale old-god encounters."
    },
    {
        id = "raid_naxxramas",
        name = "Naxxramas",
        mapID = 1415,
        x = 0.397,
        y = 0.259,
        type = "RAID",
        levelMin = 60,
        levelMax = 60,
        recommendedPlayers = 40,
        tags = { "raid", "classic" },
        description = "The final Classic Era necropolis raid above Eastern Plaguelands."
    },
}
